local ServerScriptService = game:GetService("ServerScriptService")
local SystemFolder = ServerScriptService:WaitForChild("Systems")

local CollisionHandler = require(SystemFolder:WaitForChild("CollisionHandler"))
local DragHandler = require(SystemFolder:WaitForChild("DragHandler"))
local NPCHandler = require(SystemFolder:WaitForChild("NPCHandler"))
local ObjectsHandler = require(SystemFolder:WaitForChild("ObjectsHandler"))

task.defer(function()
	CollisionHandler.init()
end)
task.defer(function()
	DragHandler.init()
end)
task.defer(function()
	ObjectsHandler.init()
end)
task.defer(function()
	task.wait(1)
	NPCHandler.init()
end)
